server:
  port: 8080
#  servlet:
#    context-path: /boot
  tomcat:
    #tomcat最大连接数
    max-connections: 10
    #tomcat最大线程数
    max-threads: 10

spring:
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  servlet:
    multipart:
      #上传文件的最大值
      max-file-size: 5MB
      max-request-size: 10MB
  #mysql数据库配置
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/boot
    url: jdbc:mysql://localhost:3306/boot
    password: root
    username: root
#    data-username: root
#    data-password: root

  jpa:
    #制定数据库类型
    database: mysql
    #在日志中显示sql语句
    show-sql: true
    hibernate:
      #如果数据库中存在持久化类对应的表就不创建，不存在就创建对应的表
      ddl-auto: update
      naming:
        #命名策略：遇到大写字母加"_"下划线的命名
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#上传文件
file:
  testPath: /home/killthunder/WorkSpase/uploadFile

logging:
  config: classpath:logback.xml
